spring:
  datasource:
    url:  jdbc:mysql://132.232.54.67:3306/gsjlpt?useUnicode: true&characterEncoding: utf-8&useSSL: false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
mybatis:
  type-aliases-package: com.zxf.gsjlpt.model
  mapper-locations: classpath:mapper/*.xml
  mappers: com.zxf.gsjlpt.common.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql
  autoRuntimeDialect: true